CREATE DATABASE IF NOT EXISTS `db-aparaty`;
CREATE USER IF NOT EXISTS `268511`@`localhost`;
SET PASSWORD FOR `268511`@`localhost` = PASSWORD('albert511');
USE `db-aparaty`;
GRANT SELECT, INSERT, UPDATE ON *.* TO `268511`@`localhost`;
FLUSH PRIVILEGES;