INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (12.12, 14.6, 'Associate');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (23.33, 11.8, 'Executive');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (14.21, 36.6, 'Technician');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (46.04, 87.9, 'Associate');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (92.83, 24.0, 'Producer');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (73.58, 81.8, 'Representa');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (82.61, 85.9, 'Officer');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (31.62, 72.9, 'Engineer');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (75.76, 52.4, 'Architect');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (30.62, 54.1, 'Manager');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (35.07, 81.4, 'Agent');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (53.38, 40.9, 'Executive');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (48.91, 66.8, 'Assistant');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (74.89, 31.2, 'Representa');
INSERT INTO Matryca (przekatna, rozdzielczosc, typ) VALUE (50.08, 15.4, 'Supervisor');

INSERT INTO Producent (nazwa, kraj) VALUE ('Nikolaus LLC', 'China');
INSERT INTO Producent (nazwa, kraj) VALUE ('Hilll Inc', 'China');
INSERT INTO Producent (nazwa, kraj) VALUE ('Orn, Cremin and Price', 'China');
INSERT INTO Producent (nazwa, kraj) VALUE ('Spinka - Cassin', 'China');
INSERT INTO Producent (nazwa, kraj) VALUE ('Schinner - Armstrong', 'China');
INSERT INTO Producent (nazwa, kraj) VALUE ('Heaney Group', 'Portugal');
INSERT INTO Producent (nazwa, kraj) VALUE ('Bode, Hahn and Auer', 'Madagascar');
INSERT INTO Producent (nazwa, kraj) VALUE ('Glover Group', 'Monaco');
INSERT INTO Producent (nazwa, kraj) VALUE ('Cassin - DAmore', 'Kiribati');
INSERT INTO Producent (nazwa, kraj) VALUE ('Rosenbaum and Sons', 'Mali');
INSERT INTO Producent (nazwa, kraj) VALUE ('Mosciski - OConnell', 'Lao Peoples');
INSERT INTO Producent (nazwa, kraj) VALUE ('Fadel Inc', 'British Indian Ocean');
INSERT INTO Producent (nazwa, kraj) VALUE ('Kemmer Group', 'Maldives');
INSERT INTO Producent (nazwa, kraj) VALUE ('Weber LLC', 'Kyrgyz Republic');
INSERT INTO Producent (nazwa, kraj) VALUE ('Bayer LLC', 'Saint Kitts');

INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('Dollar', 50036.97, 75867.51);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('Exclusive', 77499.93, 88174.85);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('Wooden', 99.27, 15544.81);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('circuit', 21041.76, 49179.8);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('bypassing', 69201.32, 85291.23);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('payment', 940.04, 18563.44);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('wireless', 35395.81, 98509.48);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('Robust', 38429.83, 45932.48);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('up', 9552.5, 21835.7);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('Representative', 6937.78, 69899.66);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('Movies', 729.27, 42622.79);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('Shoes', 672.33, 46807.59);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('Iowa', 733.35, 19110.04);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('web-readiness', 974.15, 14635.55);
INSERT INTO Obiektyw (model, minPrzeslona, maxPrzeslona) VALUE ('optical', 8851.74, 60660.9);

INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('bricks-and-clicks', 9, 107, 1, 'profesjonalny');
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('Handmade', 7, 101, 2, 'kompaktowy');
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('Dollar', 1, 106, 12, 'lustrzanka')
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('transmitting', 1, 114, 2, 'profesjonalny');
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('Account', 1, 109, 1, 'lustrzanka');
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('Licensed', 11, 107, 5, 'kompaktowy');
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('Digitized', 6, 112, 1, 'profesjonalny');
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('JSON', 6, 103, 2, 'inny');
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('red', 6, 102, 1, 'lustrzanka');
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('supply-chains', 3, 108, 6, 'kompaktowy');
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('Directives', 1, 110, 2, 'inny');
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('Lithuanian', 3, 105, 9, 'profesjonalny');
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('Fantastic', 9, 110, 5, 'kompaktowy');
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('JSONN', 7, 108, 8, 'inny');
INSERT INTO Aparat (model, producent, matryca, obiektyw, typ) VALUE ('bypass', 9, 107, 3, 'lustrzanka');
